// Package spec_3_1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package spec_3_1

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CompoundFilterType.
const (
	And CompoundFilterType = "and"
	Or  CompoundFilterType = "or"
)

// Valid indicates whether the value is a known member of the CompoundFilterType enum.
func (e CompoundFilterType) Valid() bool {
	switch e {
	case And:
		return true
	case Or:
		return true
	default:
		return false
	}
}

// Defines values for LeafFilterType.
const (
	Leaf LeafFilterType = "leaf"
)

// Valid indicates whether the value is a known member of the LeafFilterType enum.
func (e LeafFilterType) Valid() bool {
	switch e {
	case Leaf:
		return true
	default:
		return false
	}
}

// CompoundFilter Combine multiple filters using `and` or `or`.
type CompoundFilter struct {
	Filters []CompoundFilter_Filters_Item `json:"filters"`
	Type    CompoundFilterType            `json:"type"`
}

// CompoundFilter_Filters_Item defines model for CompoundFilter.filters.Item.
type CompoundFilter_Filters_Item struct {
	union json.RawMessage
}

// CompoundFilterType defines model for CompoundFilter.Type.
type CompoundFilterType string

// LeafFilter defines model for LeafFilter.
type LeafFilter struct {
	Key  *string        `json:"key,omitempty"`
	Type LeafFilterType `json:"type"`
}

// LeafFilterType defines model for LeafFilter.Type.
type LeafFilterType string

// AsLeafFilter returns the union data inside the CompoundFilter_Filters_Item as a LeafFilter
func (t CompoundFilter_Filters_Item) AsLeafFilter() (LeafFilter, error) {
	var body LeafFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLeafFilter overwrites any union data inside the CompoundFilter_Filters_Item as the provided LeafFilter
func (t *CompoundFilter_Filters_Item) FromLeafFilter(v LeafFilter) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since LeafFilter's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("LeafFilter")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeLeafFilter performs a merge with any union data inside the CompoundFilter_Filters_Item, using the provided LeafFilter
func (t *CompoundFilter_Filters_Item) MergeLeafFilter(v LeafFilter) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since LeafFilter's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("LeafFilter")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCompoundFilter returns the union data inside the CompoundFilter_Filters_Item as a CompoundFilter
func (t CompoundFilter_Filters_Item) AsCompoundFilter() (CompoundFilter, error) {
	var body CompoundFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCompoundFilter overwrites any union data inside the CompoundFilter_Filters_Item as the provided CompoundFilter
func (t *CompoundFilter_Filters_Item) FromCompoundFilter(v CompoundFilter) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since CompoundFilter's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("CompoundFilter")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeCompoundFilter performs a merge with any union data inside the CompoundFilter_Filters_Item, using the provided CompoundFilter
func (t *CompoundFilter_Filters_Item) MergeCompoundFilter(v CompoundFilter) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since CompoundFilter's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("CompoundFilter")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CompoundFilter_Filters_Item) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CompoundFilter_Filters_Item) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "CompoundFilter":
		return t.AsCompoundFilter()
	case "LeafFilter":
		return t.AsLeafFilter()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CompoundFilter_Filters_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CompoundFilter_Filters_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
