// Package spec_3_1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package spec_3_1

// Defines values for WidgetCreatedType.
const (
	WidgetCreatedTypeWidgetCreated WidgetCreatedType = "widget.created"
)

// Valid indicates whether the value is a known member of the WidgetCreatedType enum.
func (e WidgetCreatedType) Valid() bool {
	switch e {
	case WidgetCreatedTypeWidgetCreated:
		return true
	default:
		return false
	}
}

// WidgetCreated Sent when a widget is created.
type WidgetCreated struct {
	Id   string            `json:"id"`
	Name string            `json:"name"`
	Type WidgetCreatedType `json:"type"`
}

// WidgetCreatedType defines model for WidgetCreated.Type.
type WidgetCreatedType string

// WidgetCreatedJSONRequestBody defines body for WidgetCreated for application/json ContentType.
type WidgetCreatedJSONRequestBody = WidgetCreated
