// Package spec_3_1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package spec_3_1

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Defines values for TurnDetection0Type.
const (
	ServerVad TurnDetection0Type = "server_vad"
)

// Valid indicates whether the value is a known member of the TurnDetection0Type enum.
func (e TurnDetection0Type) Valid() bool {
	switch e {
	case ServerVad:
		return true
	default:
		return false
	}
}

// Defines values for TurnDetection1Eagerness.
const (
	High   TurnDetection1Eagerness = "high"
	Low    TurnDetection1Eagerness = "low"
	Medium TurnDetection1Eagerness = "medium"
)

// Valid indicates whether the value is a known member of the TurnDetection1Eagerness enum.
func (e TurnDetection1Eagerness) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for TurnDetection1Type.
const (
	SemanticVad TurnDetection1Type = "semantic_vad"
)

// Valid indicates whether the value is a known member of the TurnDetection1Type enum.
func (e TurnDetection1Type) Valid() bool {
	switch e {
	case SemanticVad:
		return true
	default:
		return false
	}
}

// TurnDetection defines model for TurnDetection.
type TurnDetection struct {
	union json.RawMessage
}

// TurnDetection0 defines model for .
type TurnDetection0 struct {
	Threshold *float32           `json:"threshold,omitempty"`
	Type      TurnDetection0Type `json:"type"`
}

// TurnDetection0Type defines model for TurnDetection.0.Type.
type TurnDetection0Type string

// TurnDetection1 defines model for .
type TurnDetection1 struct {
	Eagerness *TurnDetection1Eagerness `json:"eagerness,omitempty"`
	Type      TurnDetection1Type       `json:"type"`
}

// TurnDetection1Eagerness defines model for TurnDetection.1.Eagerness.
type TurnDetection1Eagerness string

// TurnDetection1Type defines model for TurnDetection.1.Type.
type TurnDetection1Type string

// AsTurnDetection0 returns the union data inside the TurnDetection as a TurnDetection0
func (t TurnDetection) AsTurnDetection0() (TurnDetection0, error) {
	var body TurnDetection0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTurnDetection0 overwrites any union data inside the TurnDetection as the provided TurnDetection0
func (t *TurnDetection) FromTurnDetection0(v TurnDetection0) error {
	v.Type = "server_vad"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTurnDetection0 performs a merge with any union data inside the TurnDetection, using the provided TurnDetection0
func (t *TurnDetection) MergeTurnDetection0(v TurnDetection0) error {
	v.Type = "server_vad"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTurnDetection1 returns the union data inside the TurnDetection as a TurnDetection1
func (t TurnDetection) AsTurnDetection1() (TurnDetection1, error) {
	var body TurnDetection1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTurnDetection1 overwrites any union data inside the TurnDetection as the provided TurnDetection1
func (t *TurnDetection) FromTurnDetection1(v TurnDetection1) error {
	v.Type = "semantic_vad"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTurnDetection1 performs a merge with any union data inside the TurnDetection, using the provided TurnDetection1
func (t *TurnDetection) MergeTurnDetection1(v TurnDetection1) error {
	v.Type = "semantic_vad"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TurnDetection) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t TurnDetection) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "semantic_vad":
		return t.AsTurnDetection1()
	case "server_vad":
		return t.AsTurnDetection0()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t TurnDetection) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TurnDetection) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
