// Package spec_3_1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package spec_3_1

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Defines values for Envelope0Type.
const (
	Envelope0TypeEnvelope0 Envelope0Type = "envelope0"
)

// Valid indicates whether the value is a known member of the Envelope0Type enum.
func (e Envelope0Type) Valid() bool {
	switch e {
	case Envelope0TypeEnvelope0:
		return true
	default:
		return false
	}
}

// Defines values for Envelope1Type.
const (
	Envelope1TypeEnvelope1 Envelope1Type = "envelope1"
)

// Valid indicates whether the value is a known member of the Envelope1Type enum.
func (e Envelope1Type) Valid() bool {
	switch e {
	case Envelope1TypeEnvelope1:
		return true
	default:
		return false
	}
}

// Defines values for LeafAType.
const (
	LeafATypeLeafA LeafAType = "leafA"
)

// Valid indicates whether the value is a known member of the LeafAType enum.
func (e LeafAType) Valid() bool {
	switch e {
	case LeafATypeLeafA:
		return true
	default:
		return false
	}
}

// Defines values for LeafBType.
const (
	LeafBTypeLeafB LeafBType = "leafB"
)

// Valid indicates whether the value is a known member of the LeafBType enum.
func (e LeafBType) Valid() bool {
	switch e {
	case LeafBTypeLeafB:
		return true
	default:
		return false
	}
}

// Envelope defines model for Envelope.
type Envelope struct {
	union json.RawMessage
}

// Envelope0 defines model for Envelope0.
type Envelope0 struct {
	Type  Envelope0Type `json:"type"`
	Value *string       `json:"value,omitempty"`
}

// Envelope0Type defines model for Envelope0.Type.
type Envelope0Type string

// Envelope1 defines model for Envelope1.
type Envelope1 struct {
	Type  *Envelope1Type `json:"type,omitempty"`
	Value *string        `json:"value,omitempty"`
}

// Envelope1Type defines model for Envelope1.Type.
type Envelope1Type string

// LeafA defines model for LeafA.
type LeafA struct {
	A    *string   `json:"a,omitempty"`
	Type LeafAType `json:"type"`
}

// LeafAType defines model for LeafA.Type.
type LeafAType string

// LeafB defines model for LeafB.
type LeafB struct {
	B    *string   `json:"b,omitempty"`
	Type LeafBType `json:"type"`
}

// LeafBType defines model for LeafB.Type.
type LeafBType string

// NestedUnion defines model for NestedUnion.
type NestedUnion struct {
	union json.RawMessage
}

// AsEnvelope0 returns the union data inside the Envelope as a Envelope0
func (t Envelope) AsEnvelope0() (Envelope0, error) {
	var body Envelope0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEnvelope0 overwrites any union data inside the Envelope as the provided Envelope0
func (t *Envelope) FromEnvelope0(v Envelope0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since Envelope0's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("Envelope0")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeEnvelope0 performs a merge with any union data inside the Envelope, using the provided Envelope0
func (t *Envelope) MergeEnvelope0(v Envelope0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since Envelope0's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("Envelope0")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEnvelope1 returns the union data inside the Envelope as a Envelope1
func (t Envelope) AsEnvelope1() (Envelope1, error) {
	var body Envelope1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEnvelope1 overwrites any union data inside the Envelope as the provided Envelope1
func (t *Envelope) FromEnvelope1(v Envelope1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since Envelope1's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("Envelope1")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeEnvelope1 performs a merge with any union data inside the Envelope, using the provided Envelope1
func (t *Envelope) MergeEnvelope1(v Envelope1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since Envelope1's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("Envelope1")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNestedUnion returns the union data inside the Envelope as a NestedUnion
func (t Envelope) AsNestedUnion() (NestedUnion, error) {
	var body NestedUnion
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNestedUnion overwrites any union data inside the Envelope as the provided NestedUnion
func (t *Envelope) FromNestedUnion(v NestedUnion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since NestedUnion's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("NestedUnion")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeNestedUnion performs a merge with any union data inside the Envelope, using the provided NestedUnion
func (t *Envelope) MergeNestedUnion(v NestedUnion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since NestedUnion's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("NestedUnion")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Envelope) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Envelope) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "Envelope0":
		return t.AsEnvelope0()
	case "Envelope1":
		return t.AsEnvelope1()
	case "NestedUnion":
		return t.AsNestedUnion()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Envelope) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Envelope) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsLeafA returns the union data inside the NestedUnion as a LeafA
func (t NestedUnion) AsLeafA() (LeafA, error) {
	var body LeafA
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLeafA overwrites any union data inside the NestedUnion as the provided LeafA
func (t *NestedUnion) FromLeafA(v LeafA) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since LeafA's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("LeafA")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeLeafA performs a merge with any union data inside the NestedUnion, using the provided LeafA
func (t *NestedUnion) MergeLeafA(v LeafA) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since LeafA's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("LeafA")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLeafB returns the union data inside the NestedUnion as a LeafB
func (t NestedUnion) AsLeafB() (LeafB, error) {
	var body LeafB
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLeafB overwrites any union data inside the NestedUnion as the provided LeafB
func (t *NestedUnion) FromLeafB(v LeafB) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since LeafB's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("LeafB")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeLeafB performs a merge with any union data inside the NestedUnion, using the provided LeafB
func (t *NestedUnion) MergeLeafB(v LeafB) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// The discriminator property is set on the marshaled JSON directly rather
	// than on the Go struct field, since LeafB's discriminator field may be
	// absent, optional (pointer), or of a named type incompatible with a bare
	// string literal.
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	object["type"], err = json.Marshal("LeafB")
	if err != nil {
		return err
	}
	b, err = json.Marshal(object)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NestedUnion) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t NestedUnion) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "LeafA":
		return t.AsLeafA()
	case "LeafB":
		return t.AsLeafB()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t NestedUnion) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NestedUnion) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
